### ISSUE TITLE
design question

### ISSUE THREAD

**Issue by kml-pt** [cjbaar/prusa-mmu-12x#1]
Impressive project! What CAD platform did you use for the design? Would you be willing to share the CAD files? I would like to put different sized fittings on the inlet.

**Comment by cjbaar** [comment]
Sorry, not currently prepared to share the source files. There are options for m6 and m10 fittings, and someone else did a mix for a push fitting like the original Prusa one uses. What fitting are you looking to use?

**Comment by kml-pt** [comment]
I like to tap an unthreaded 4.2mm hole to use with m5 fittings. But I went ahead with your m10 design and liked it more than I thought I would.

**Comment by cjbaar** [comment]
The m10 is definitely my favorite, as it lets me get the PTFE all the way up to the exit point, so IMO less risk of catching on the fitting itself. Another user made a re-mix of selector for 12x, but allows the use of the heat-set insert like Prusa used. See if this is what you are looking for. I haven't added it the repo yet.
[HeatSet-mmu12x-selector-v1.1.stl.zip](https://github.com/cjbaar/prusa-mmu-12x/files/5997583/HeatSet-mmu12x-selector-v1.1.stl.zip)

**Comment by 3d-gussner** [comment]
@cjbaar Do you plan to provide the cad files at some point? If not a problem, just asking before trying to convert the STL files to STEP or cad files manually.

**Comment by cjbaar** [comment]
Sorry, not at this time. Is there something specific you are looking to modify?

**Comment by 3d-gussner** [comment]
> Sorry, not at this time. Is there something specific you are looking to modify?

No problem. I was looking at the STL files and the config changes you have made.
If I am not mistaken the idler bearings are 25° of each other but in the config.h you have 25.4° See https://github.com/cjbaar/Prusa-Firmware-MMU-12x/blob/main/src/config/config.h#L213

Maybe I didn't convert the STL correctly to a STEP/ Fusion360 and am there off by 0.4°

**Comment by cjbaar** [comment]
They are 25.2° by design, but I found that 25.4° worked better in the code for proper alignment. Something about the motor steps, perhaps? It's a very small adjustment.

**Comment by 3d-gussner** [comment]
> They are 25.2° by design, but I found that 25.4° worked better in the code for proper alignment. Something about the motor steps, perhaps? It's a very small adjustment.

Calculating the degrees to actual steps is very hard. The NEMA has 200 Steps per rotation and so 1.8° per full step. With microsteps you get it better. The 32u4 has very limited resources and calculating floats isn't easy here.
Actually your 25.2° are "perfect" full steps (25.2/1.8=14) but you never know what the home position is and so the stepper is probably all the time in some microsteps.

3D printed parts + bearings + tolerances add up quickly and often the "perfect" 25.2° in CAD are in real world 25.4°
