### ISSUE TITLE
Updated firmware please!!

### ISSUE THREAD

**Issue by Johnday29** [cjbaar/prusa-mmu-12x#14]
Any chance of getting new firmware with the update to fix the max T4?  The current firmware keeps crashing on my printer saying that the bed had temp issues even though the temp was just fine!

**Comment by cjbaar** [comment]
I have updated release 3.11.0 with the necessary changes for tools above T4. It is on my fork of PrusaFirmware, and there is a compiled MK3S version in the firmware folder of this repo.

**Comment by Johnday29** [comment]
Thank you so much!
