### ISSUE TITLE
Question About Print Material

### ISSUE THREAD

**Issue by sabaatworld** [cjbaar/prusa-mmu-12x#15]
Thank you for keeping the project alive. I'm thinking of building this and was wondering if you would still recommend PLA as material of choice, based on your long term experience with your setup?

**Comment by cjbaar** [comment]
I printed everything in PLA. Others have used PETG, but not sure if you would find the tolerances different.

**Comment by grzlus** [comment]
PLA works fine. I printed a lot with it and it just works.
