### ISSUE TITLE
mmu12x-lower-mod.stl is damaged

### ISSUE THREAD

**Issue by renoxray** [cjbaar/prusa-mmu-12x#17]
Hi @cjbaar,

I finally trying to build one mu 2x based on my exist mmu2s and I found the mmu12x-lower-mod.stl come with only 78.6k size.

Could you help to update it :)

![image](https://user-images.githubusercontent.com/62172632/229071772-64ffb3da-53c0-44ab-8751-9234c235c520.png)

**Comment by grzlus** [comment]
This looks like a modifier to the file `mmu12x-lower.stl`. You can use it to disable or enforce supports

**Comment by renoxray** [comment]
@grzlus 

Thanks for the help. I've just realized the mod part is for this purpose.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/62172632/229328631-183070a5-3dab-4681-bfda-b4a055b10518.png">
