### ISSUE TITLE
Looks like fun project

### ISSUE THREAD

**Issue by rmilyard** [cjbaar/prusa-mmu-12x#3]
I have bunch extra MMU2 parts and was looking for something like this to undertake.  Just wondering if have more detail build or guide yet?

**Comment by rmilyard** [comment]
Looking for info as how wire in OLED also

**Comment by Huang-TS** [comment]
I can't wait to watch some demo video about this nice project.

**Comment by rmilyard** [comment]
I am working on prints now.  Using PLA CF.
