### ISSUE TITLE
Attach Upper and Lower

### ISSUE THREAD

**Issue by rmilyard** [cjbaar/prusa-mmu-12x#6]
What did you use here to mount these together?

![IMG_0064](https://user-images.githubusercontent.com/11091710/116410022-3bf40b00-a7e9-11eb-87c2-cb68e17f6aeb.JPG)
![IMG_0065](https://user-images.githubusercontent.com/11091710/116410033-3d253800-a7e9-11eb-90b4-f8b70b4bc844.JPG)

**Comment by cjbaar** [comment]
Sorry @rmilyard my email responses to you are being blocked by Hotmail for some reason. I used M5 screws, which should thread loosely into the hole on the upper piece. You could also try the 5mm pins from the original, but they might be too tight.
