### ISSUE TITLE
mmu12x-inlet is not a manifold

### ISSUE THREAD

**Issue by KaruroChori** [cjbaar/prusa-mmu-12x#9]
Trying to slice mmu12x-inlet in cura will result in visible holes on top of the geometry.
SuperSlicer with a similar profile is able to repair the mesh before slicing.

**Comment by cjbaar** [comment]
PrusaSlic3r tells me "Auro-repaired 10 errors." The top gets a bit odd with the slight angle on the threads, but I have printed the part several times without issue.

**Comment by KaruroChori** [comment]
Yes, same as with SuperSlicer; as they are both forks of Slic3r it does make sense I guess.
I was able to print it just as you said, which is why I had closed this issue.

Btw, thank you for sharing. It is going to be a lot of fun!
